version: '3.8'

services:
  opensips:
    image: opensips:opensips_arm64-3.4.11  
    # environment:
    #   # Add any environment variables here if needed
    volumes:
      - ./opensips.cfg:/usr/local/etc/opensips/opensips.cfg
    networks:
      opensips_cluster:
        ipv4_address: 172.168.34.51
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "opensipsctl", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mydatabase
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     opensips_cluster:
  #       ipv4_address: 172.168.34.52
  #   restart: unless-stopped

  # adminer:
  #   image: adminer:latest
  #   container_name: adminer
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     ADMINER_DEFAULT_SERVER: postgres
  #   depends_on:
  #     - postgres
  #   networks:
  #     opensips_cluster:
  #       ipv4_address: 172.168.34.53
  #   restart: unless-stopped

networks:
  opensips_cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.34.0/24

# volumes:
#   postgres_data: